# theme: jekyll-theme-architect
# GitHub Stars: https://github.com/dawidolko/Website-Templates
# icon: logo.png
favicon: "logo.png"
title: 170 HTML5 Website Templates - free editable templates
description: 170 HTML5 Website Templates - free editable templates
GitHub Stars: https://github.com/dawidolko/Website-Templates
icon: logo.png
favicon: "logo.png"
show_downloads: true
theme: jekyll-theme-midnight
